apiVersion: apps/v1
kind: Deployment
metadata:
  name: machineinfo
  labels:
    app: machineinfo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: machineinfo
  template:
    metadata:
      labels:
        app: machineinfo
    spec:
      containers:
      - name: machineinfo
        image: sirasaoa/machineinfo:v1.2
        envFrom:
        - configMapRef:
            name: sample-configmap
        ports:
        - containerPort: 9000
